### ISSUE TITLE
Screen goes blank when trying to add Supplies & Farms

### ISSUE THREAD

**Issue by nickwxo** [slashroots/jas-mis-app#91] opened 2015-08-10 21:38 UTC
The actual issue that we've discovered here is that the existing code does not gracefully handle situations where no supplies or farms matching the search string are found. 

1) We get 500 errors (internal server errors) from the ajax call to the crops endpoint with the 'beginsWith' parameter.

2) We also get a Javascript error complaining about trying to read "success" of undefined which is almost certainly an ajax issue.

The screen itself goes blank because at the time of the error the body element gets some strange css of -1000 + pixels top (and position fixed) applied to it but the underlying issue remains the bugs with the search query function. Hoping @matjames007 can help guide us on this one.

**Comment by matjames007** [comment] 2015-08-10 22:09
@nick22891 or @tremainebuchanan what branch are you guys on?  Give me some steps to reproduce this.

**Comment by tremainebuchanan** [comment] 2015-08-10 23:15
@matjames007 not sure which branch he was working on today. But since your comment I did a test on my supply-input-impl branch and I didn't encounter the error.

**Comment by paradoxxjm** [comment] 2015-08-11 00:58
@matjames007 @tremainebuchanan, if you go to the staging deployment you will experience this erorr. Steps to recreate it include:
1. Go to a particular farmer page e.g ![Application Link](https://jas-mis-app-staging.herokuapp.com/home#/farmer/559d11ae829bcad12cfb18b3)
2. Click the "Add" button to create a new supply
3. Start typing the name of a crop name (e.g Banana). Upon reach the first "n" character the screen will turn blank similar to what Nick has described.
![jasmicnewcropbug](https://cloud.githubusercontent.com/assets/406181/9187790/21d53716-3f9a-11e5-86e4-153c109ad2d7.png)

Let me know if you are able to recreate the above

**Comment by matjames007** [comment] 2015-08-11 02:44
uggggh.... this is one of those bugs that keeps you up at night...really isn't anyone's fault.  @nick22891, @tremainebuchanan and @paradoxxjm.... angular material does it again.  I downgraded to angular material 0.9.0 and it functions perfectly.  I am currently reviewing the [changelog](https://github.com/angular/material/blob/master/CHANGELOG.md) for angular material to see if I can remedy the situtation.

**Comment by matjames007** [comment] 2015-08-11 12:03
Update:  There were major changes to `md-autocomplete` after version 0.9 of angular material. 

The problem experienced occurs on all pages with the autocomplete element.  I checked and ensured the issue isn't a css one.  I suspect that it is a bug with that occurs after the angular team fixed this documented bug: [Locks scrolling while autocomplete menu is visible](https://github.com/angular/material/commit/deae957b)

**Comment by paradoxxjm** [comment] 2015-08-11 12:06
So is this fixed by just rolling back to a previous version of angular?

**Comment by matjames007** [comment] 2015-08-11 12:13
nah, i think we should try and follow the updated angular material docs and ensure that we have matched the new usage as best as possible.

**Closed as completed** 2015-08-26 21:05 UTC
Labels: bug, help wanted
